# Generated by Django 4.2.3 on 2023-07-31 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=500)),
                ('prezzo', models.FloatField()),
                ('quantita', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Amministratore',
            fields=[
                ('utente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applicazione.utente')),
            ],
            bases=('applicazione.utente',),
        ),
        migrations.CreateModel(
            name='ProdottoVenduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=100)),
                ('descrizione', models.CharField(max_length=500)),
                ('prezzo', models.FloatField()),
                ('quantita', models.IntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti_venduti', to='applicazione.stock')),
            ],
        ),
        migrations.CreateModel(
            name='ProdottoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField()),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='applicazione.carrello')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicazione.prodotto')),
            ],
        ),
        migrations.AddField(
            model_name='prodotto',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='applicazione.stock'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('utente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='applicazione.utente')),
                ('carrello', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicazione.carrello')),
            ],
            bases=('applicazione.utente',),
        ),
    ]
