# Generated by Django 4.2.3 on 2023-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
