# Generated by Django 4.2.3 on 2023-07-31 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrello',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrello', to=settings.AUTH_USER_MODEL),
        ),
    ]
