# Generated by Django 4.2.3 on 2023-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0002_stock_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='nome',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
