# Generated by Django 4.2.3 on 2023-07-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicazione', '0003_alter_stock_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='applicazione.stock'),
        ),
        migrations.AlterField(
            model_name='prodottocarrello',
            name='carrello',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='applicazione.carrello'),
        ),
    ]
